- hosts: all

  tasks:

    - name: Update apt-cache
      apt: update_cache=yes

    - name: Download python tar.xz
      get_url: url=https://www.python.org/ftp/python/3.5.3/Python-3.5.3rc1.tar.xz dest=/tmp/Python-3.5.3rc1.tar.xz

    - name: Extract
      shell: tar -xf Python-3.5.3rc1.tar.xz chdir=/tmp

    - name: Conf
      shell: ./configure chdir=/tmp/Python-3.5.3rc1

    - name: Make
      shell: make chdir=/tmp/Python-3.5.3rc1
#      become_user: root
#      become: yes

    - name: Install
      shell: make install chdir=/tmp/Python-3.5.3rc1
#      become: yes
#      become_user: root

    - name: Remove tmp files
      file: path={{ item }} state=absent
      with_items:
        - /tmp/Python-3.5.3rc1.tar.xz
        - /tmp/Python-3.5.3rc1
