- hosts: all

  tasks:

    - name: Update apt-cache
      apt: update_cache=yes

#    - name:    install git dependencies
#      package: name={{ item }}
#      with_items:
#        - curl-devel
#        - expat-devel
#        - gettext-devel
#        - openssl-devel
#        - perl-devel
#        - zlib-devel
#        - autoconf
#        - gcc

    - name: Install packages
      apt: pkg={{ item }}
      with_items:
        - wget
        - xz-utils
        - build-essential
        - libsqlite3-dev
        - libreadline-dev
        - libssl-dev
        - openssl
        - sudo
#        - curl-devel
#        - expat-devel
#        - gettext-devel
#        - openssl-devel
#       - zlib-devel

    - name: install python3 packages
      apt: "pkg={{ item }} state=latest"
      with_items:
        - python3
        - python3-venv
        - python3-dev
        - build-essential
        - python-pip
        - python-setuptools
        - git
#        - vim
        - htop
        - nload
        - libzmq3-dev
        - postgresql
        - postgresql-server-dev-9.6
        - libjpeg-dev
        - libfreetype6-dev
        - zlib1g-dev
        - make
        - gcc
        - g++
        - pkg-config
        - libsodium-dev
        - libtool
        - pkg-config
        - build-essential
        - autoconf
        - automake
        - python-virtualenv
        - supervisor
#        - wget
#        - xz-utils
#        - build-essential
#        - libsqlite3-dev
#        - libreadline-dev
#        - libssl-dev
#        - openssl
